replicaCount: 1

image:
  repository: ghcr.io/benc-uk/kubeview
  tag: latest
  pullPolicy: IfNotPresent

loadBalancer:
  enabled: false

nodePort:
  enabled: true
  port: 32080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
